### PR TITLE
Draft DeploymentEvent specification

### PR DESCRIPTION
**Pull request by kimtore**
https://github.com/navikt/pig/blob/master/PIG-Deployment/adr/000-deployment-event-kafka.md

### CODE REVIEW

**Comment by kimtore** [comment]
A few suggestions:

* rename message `EnvironmentClass` to `Environment` so that it is easier to understand and re-use
* rename `environment` to `environmentDivision` or similar
* rename message `Deployer` to `Actor`, leave variable unchanged
* rename message `Source` to `Reporter`

What do you think?

**Comment by jhrv** [comment]
I'm ok with the suggestion except environmentDivision. Maybe for legacy we can just use namespace here instead?

**Comment by kimtore** [comment]
> I'm ok with the suggestion except environmentDivision. Maybe for legacy we can just use namespace here instead?

Instead of overloading fields with context-sensitive purpose, let's try naming them so that there is no ambiguity of what they mean. Any suggestions for a new name?

* `SubEnvironment`
* `EnvironmentEnumeration`
* `EnvironmentFacet`

**Comment by kimtore** [comment]
@matsbyfl @jhrv request for approval on the latest revision.

**Review by jhrv — APPROVED** [review]
lgtm

**Pull request merged**
